export const buttonStyle = {
    thinBlue: {
        height: "20px",
        fontSize: "12px",
        padding: "7px 16px 4px",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#ffffff",
        borderStyle: "solid",
        borderWidth: "1px",
        borderColor: "#dcdcdc",
        color: "#2263ff",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        marginRight: 5
    },
    thinGreen: {
        height: "20px",
        fontSize: "12px",
        padding: "7px 16px 4px",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#ffffff",
        borderStyle: "solid",
        borderWidth: "1px",
        borderColor: "#dcdcdc",
        color: "#0dbf0d",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        marginRight: 5
    },
    thinSkypePurp: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderStyle: "solid",
        borderWidth: "1px",
        borderColor: "#00aff0",
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#ffffff",
        color: "#00aff0",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thinJoin: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 1,
        fontWeight: 500,
        borderStyle: "solid",
        borderWidth: "2px",
        borderColor: "#F0F2F6",
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#ffffff",
        color: "#6094F7",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thinQuoteGreen: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderStyle: "solid",
        borderWidth: "1px",
        borderColor: "#12dc91",
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#ffffff",
        color: "#12dc91",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thickBlue: {
        height: "60px",
        fontSize: "14px",
        //paddingTop: "10px",
        paddingBottom:"10px";
        //width: "100%",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "rgb(19, 30, 53)",
        color: "#ffffff",
        boxShadow: "0 1px 1px rgba(0,0,0,.3)",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thickSkype: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#00aff0",
        color: "#ffffff",
        boxShadow: "0 1px 1px rgba(0,0,0,.3)",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thickSkypePurp: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#00aff0",
        color: "#ffffff",
        boxShadow: "0 1px 1px rgba(0,0,0,.3)",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none",
        cursor: "pointer"
    },
    thickGreen: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#02d44c",
        color: "#ffffff",
        boxShadow: "0 1px 1px rgba(0,0,0,.3)",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none"
    },
    thickRed: {
        height: "30px",
        fontSize: "14px",
        paddingTop: "10px",
        width: "100%",
        border: 0,
        borderRadius: "3px",
        lineHeight: "inherit",
        backgroundColor: "#fd658f",
        color: "#ffffff",
        boxShadow: "0 1px 1px rgba(0,0,0,.3)",
        position: "relative",
        top: 0,
        marginTop: "15px!important",
        display: "inline-block",
        verticalAlign: "middle",
        userSelect: "none",
        textAlign: "center",
        textDecoration: "none"
    },
    icon: {
        height: 11,
        width: 11,
        marginRight: 5,
        display: "inline-block",
        verticalAlign: "middle"
    }
}